from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.util import Inches
from pptx.enum.shapes import MSO_SHAPE

#for chart
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.util import Inches

#path = 'temp.pptx'
prs = Presentation()

#1slide
title_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
subtitle

title.text = "This slide was generated by python scripts"
subtitle.text = "https://github.com/YuiM/python-ppt-generate"

#2slide
bullet_slide_layout = prs.slide_layouts[1]

slide = prs.slides.add_slide(bullet_slide_layout)
title = slide.shapes.title
title.text = "Verification,!"
shapes = slide.shapes

title_shape = shapes.title
body_shape = shapes.placeholders[1]

title_shape.text = 'Adding a Bullet Slide'

tf = body_shape.text_frame
tf.text = 'Find the bullet slide layout'

p = tf.add_paragraph()
p.text = 'Use _TextFrame.text for first bullet'
p.level = 1

p = tf.add_paragraph()
p.text = 'Use _TextFrame.add_paragraph() for subsequent bullets'
p.level = 2

p = tf.add_paragraph()
p.text = 'Use _TextFrame.add_paragraph() for subsequent bullets_2'
p.level = 2

p = tf.add_paragraph()
p.text = 'Use _TextFrame.add_paragraph() for subsequent bullets_2'
p.level = 1

p = tf.add_paragraph()
p.text = 'Use _TextFrame.add_paragraph() for subsequent bullets_2'
p.level = 2

#slide3
blank_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(blank_slide_layout)
title = slide.shapes.title
title.text = "Release,!"

left = Inches(1)
top = Inches(2)
width = height = Inches(1)

txBox = slide.shapes.add_textbox(left, top, width, height)
tf = txBox.text_frame

tf.text = "This is text inside a textbox"

p = tf.add_paragraph()
p.text = "This is a second paragraph that's bold"
p.font.bold = True

p = tf.add_paragraph()
p.text = "This is a third paragraph that's big"
p.font.size = Pt(40)
p.font.color.rgb = RGB(12, 34, 56)
Debug.Print font.Color.RGB

#slide4

img_path = 'ac_01_02.png'
blank_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(blank_slide_layout)

left = top = Inches(2)
pic = slide.shapes.add_picture(img_path, left, top)

#left = Inches(5)
#height = Inches(5.5)
#pic = slide.shapes.add_picture(img_path, left, top, height=height)

title_only_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(title_only_slide_layout)
shapes = slide.shapes

shapes.title.text = 'Adding an AutoShape'

left = Inches(0.93)  # 0.93" centers this overall set of shapes
top = Inches(3.0)
width = Inches(1.75)
height = Inches(1.0)

shape = shapes.add_shape(MSO_SHAPE.PENTAGON, left, top, width, height)
shape.text = 'Step 1'
left = left + width - Inches(0.4)
width = Inches(2.0)  # chevrons need more width for visual balance
for n in range(2, 6):
    shape = shapes.add_shape(MSO_SHAPE.CHEVRON, left, top, width, height)
    shape.text = 'Step %d' % n
    left = left + width - Inches(0.4)

title_only_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(title_only_slide_layout)
shapes = slide.shapes

shapes.title.text = 'Adding a Table'

rows = 6
cols = 2
left = top = Inches(2.0)
width = Inches(6.0)
height = Inches(0.8)

table = shapes.add_table(rows, cols, left, top, width, height).table

# set column widths
table.columns[0].width = Inches(2.0)
table.columns[1].width = Inches(4.0)
#table.columns[2].width = Inches(6.0)
#table.columns[3].width = Inches(8.0)
#table.columns[4].width = Inches(10.0)
#table.columns[5].width = Inches(12.0)

# write column headings
table.cell(0, 0).text = 'Foo'
table.cell(0, 1).text = 'Bar'

# write body cells
table.cell(1, 0).text = 'Baz'
table.cell(1, 1).text = 'Qux'

# write body cells
table.cell(2, 0).text = 'Fiz'
table.cell(2, 1).text = 'Buz'

# write body cells
table.cell(3, 0).text = 'FizBuz'
table.cell(3, 1).text = 'BuzFiz'

# write body cells
table.cell(4, 0).text = 'BuzBuz'
table.cell(4, 1).text = 'FizFiz'

left = Inches(1)
top = Inches(5)
width = height = Inches(1)

txBox = slide.shapes.add_textbox(left, top, width, height)
tf = txBox.text_frame

tf.text = "This is text inside a textbox"

p = tf.add_paragraph()
p.text = "This is a second paragraph that's bold"
p.font.bold = True

p = tf.add_paragraph()
p.text = "This is a third paragraph that's big"
p.font.size = Pt(40)

#slide for chart
# create presentation with 1 slide ------

slide = prs.slides.add_slide(prs.slide_layouts[5])

# define chart data ---------------------
chart_data = ChartData()
chart_data.categories = ['East', 'West']
chart_data.add_series('Series 1', (19.2, 21.4))

# add chart to slide --------------------
x, y, cx, cy = Inches(2), Inches(2), Inches(6), Inches(4.5)
slide.shapes.add_chart(
    XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data
)

prs.save('test.pptx')



